### ISSUE TITLE
Task completion when correcting segments

### ISSUE THREAD

**Issue by klschoef** [dres-dev/DRES#368] opened 2022-11-11 15:01 UTC
When there are only wrong submisson of a KIS task for all teams that are changed to correct during the task, the server does not recognize that the task is complete.

**Comment by lucaro** [comment] 2022-11-11 15:07
I'm not sure I understand the issue. You had an incorrect ground truth in a KIS task, everybody submitted a correct submission (which was counted as wrong due to the incorrect ground truth) and you manually updated overwrote the verdict for all participants while the task was still active? So the expectation was that the task would end automatically once you had overwritten the verdicts such that every team had a correct submission?

**Comment by klschoef** [comment] 2022-11-11 18:55
Today we had this issue because there was a duplicate video and we had to manually mark a lot of submissions as correct.

**Comment by lucaro** [comment] 2022-11-13 11:40
And that happened while the task was still active but after all the submissions were in?

**Comment by klschoef** [comment] 2022-11-13 19:18
Yes, the submissions were already in, which were later manually changed to 'correct'.

**Comment by lucaro** [comment] 2022-11-13 19:27
I see. This is not a bug as such, since we didn't intend these mechanisms to be used that way, but there isn't a reason why they couldn't be used this way. Having the task termination feature also consider changes made to the verdicts by admins should be reasonably straight forward to do, we'll have a look.

**Comment by klschoef** [comment] 2022-11-14 08:26
Okay, thanks!

**Comment by ppanopticon** [comment] 2023-05-08 08:47
This should be covered by the new implemented in the 2.0 release (Issue #391).

**Comment by sauterl** [comment] 2023-05-08 09:21
Closing this issue for now as it is resloved for the new version 2

**Closed by sauterl** 2023-05-08 09:21 UTC
Labels: enhancement, dev
