### ISSUE TITLE
Certain logos cause uncaught errors

### ISSUE THREAD

**Issue by silvanheller** [dres-dev/DRES#372] opened 2022-12-06 14:41 UTC
**Describe the bug**
When uploading logos, sometimes the competition builder throws unspecified errors. This is especially frustrating when creating a competition, as finding out where the faulty input is is non-trivial. (I assume the issue is logo size, but the UI should make that clear)

**To Reproduce**
Use the attached image as a logo

**Expected behavior**
A clear error message

**Screenshots**

**Environment**
 - OS: Windows
 - Browser: Firefox
 - DRES Version: 897b475c86644b1d72a3bb96c902bc4d0b964952 ~Whatever is deployed on `dmi-dres.dmi.unibas.ch` currently~ (Also bumping #355 as showing this to users would enable better bug reports) NB: on `dmi-dres.dmi.unibas.ch` is now 897b475c86644b1d72a3bb96c902bc4d0b964952 deployed.

**Additional context**
![logo-dalle](https://user-images.githubusercontent.com/14314470/205941640-7634ac61-6bdc-42b7-8c5d-cea76e5e8a75.png)

** Stacktrace**:
```
ERROR TypeError: t is null
    NT https://dmi-dres.dmi.unibas.ch/main.2a2c40966890496a.js:1
    Pb https://dmi-dres.dmi.unibas.ch/main.2a2c40966890496a.js:1
    Uu https://dmi-dres.dmi.unibas.ch/main.2a2c40966890496a.js:1
    addControl https://dmi-dres.dmi.unibas.ch/main.2a2c40966890496a.js:1
    _setUpControl https://dmi-dres.dmi.unibas.ch/main.2a2c40966890496a.js:1
    ngOnChanges https://dmi-dres.dmi.unibas.ch/main.2a2c40966890496a.js:1
    t2 https://dmi-dres.dmi.unibas.ch/main.2a2c40966890496a.js:1
    M2 https://dmi-dres.dmi.unibas.ch/main.2a2c40966890496a.js:1
    _0 https://dmi-dres.dmi.unibas.ch/main.2a2c40966890496a.js:1
    qh https://dmi-dres.dmi.unibas.ch/main.2a2c40966890496a.js:1
    Pw https://dmi-dres.dmi.unibas.ch/main.2a2c40966890496a.js:1
    E https://dmi-dres.dmi.unibas.ch/main.2a2c40966890496a.js:1
    template https://dmi-dres.dmi.unibas.ch/main.2a2c40966890496a.js:1
    ```

**Comment by silvanheller** [comment] 2022-12-09 14:11
> Github presents the attached logo as png - was that initially the case?

yes

**Comment by lucaro** [comment] 2023-07-17 14:18
Since the rework of the template editor, this issue can not be reproduced. I assume it's fixed now.

**Closed by lucaro** 2023-07-17 14:18 UTC
Labels: bug
