### ISSUE TITLE
ImportSegments not working

### ISSUE THREAD

**Issue by cristinailli** [dres-dev/DRES#201] opened 2020-11-13 09:15 UTC
When importing the segment information for a video collection, the import does not work.
There is a mismatch between names and/or ids for the videos.

**Comment by sauterl** [comment] 2020-11-20 14:28
This works as intended and was rather a configuration / setup issue.
We close this for now but have noted, that the entire segment management / handlig is poorly documented and we'll have to have a look

**Closed by sauterl** 2020-11-20 14:28 UTC
Labels: bug, urgent
