### ISSUE TITLE
Control looping of query hints

### ISSUE THREAD

**Issue by lucaro** [dres-dev/DRES#296] opened 2022-01-12 14:30 UTC
Add an explicit option to select the default behavior for whether the last query hint should be kept (looped in case of videos) or be shown once/for a fixed time amount and then go to black. This is currently already possible but requires to manually setting the duration of all elements explicitly.

**Comment by ppanopticon** [comment] 2022-02-14 17:47
The way I solve this now is by implementing a simple rule which is applied when adding a new hint:
- Item 1 start at `0` and ends at `task.duration`
- Item (n+1) starts and `(n).end` and lasts until `task.duration`

Like this, the user must only adjust the end, if they intend to have a shorter duration. 

I've been playing with different, additional rules, such as `(n+1).end = (n+1).start + ((n).end-(n).start)`. But I guess depending on what you would like to do, this will cause more harm that anything else. Any thoughts?

**Comment by ppanopticon** [comment] 2022-02-14 18:18
I just had another idea: How about we complement the (+)-Button at the top by additional (+)-Buttons for each element and then we augment these buttons with additional logic. 

In Microsoft Power Point terms, I would use phases such as:

- Add new <Hint> that starts after this <Hint>
- Add new <Hint> that start with this <Hint>

Then we can guide the users through the process. Furthermore, I would make all start and end fields required fields.

**Comment by ppanopticon** [comment] 2022-02-16 08:45
New version! Please check: As (kinda) proposed by Loris, there is now a new logic in place:

- Hints can be added to the end OR can be inserted after another hin (in which case the type is inherited)
- The duration (start / end) is now automatically and equally distributed per 'channel', assuming a linear progression
- Start / end are now required fields

Does that work?

**Comment by sauterl** [comment] 2022-02-16 08:58
Thanks - I like this verison very much and it feels intiutive.

**Comment by sauterl** [comment] 2022-02-28 14:38
Currently the issue is, for the first hint, adding another hint AFTER doesn't add _after_ - it just adds somwhere. For all other hints it works as described above.

**Comment by ppanopticon** [comment] 2022-03-08 14:50
Added new version. As discussed, the behaviour is as follows:

- New entry starts when previous entry of the same _channel_ ends and remains open ended.
- If new entry is the first entry, then start is assumed to be zero.
- If the previous entry has no defined end, a duration of 30 seconds is assumed and the end of the previous entry is updated accordingly.

This solution produces suboptimal results in following cases:
1. If the cumulative duration of all hints exceeds the duration of the task, this is neither detected nor prevented. 
2. Inserting an entry somewhere in the middle does not update the entries that follow.

1) could be addressed by a validation rule. I don't know what else we can do here. 2) could be addressed by updating all subsequent entries according to the rules stated. But I'm unsure whether this is desired. Any thoughts?

**Comment by lucaro** [comment] 2022-03-08 15:03
The described behavior sounds good to me. Regarding 1, I think a validation rule makes sense. For 2, I don't think we need to worry much about this, since in cases where people add hints in between existing ones, they will have to update stuff anyway.

**Closed** 2022-03-14 09:41 UTC
Labels: enhancement, quality-of-life, dev
